name: Scheduled Contribution

on:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  Contribute:
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub main branch
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: (temp) List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: Run Python script
        run: python ${{ github.workspace }}/main.py
      
      - name: Upload file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: job-result
          path: file.txt
