name: Scheduled Contribution

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  Test-Job:
    name: "Print to text file"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Check out GitHub main branch
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Run Python script
        run: python test_script.py
      
      - name: Upload file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: job-result
          path: file.txt
