name: Scheduled Contribution

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  Contribute:
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub main branch
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update README.md if it's a contribution day
        run: python ${{ github.workspace }}/contribute.py

      - name: Commit change
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Contribute on $(date)"
