name: Scheduled Contribution

on:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  Contribute:
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub main branch
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Python script
        run: python ${{ github.workspace }}/main.py

      - name: Update README.md file
        run: echo "Updated on $(date)" > ${{ github.workspace }}/README.md

      - name: Commit change
        run: |
          git config --local user.name the-contributron
          git config --local user.email ${{ secrets.EMAIL }}
          git commit -am "feat: Contribute on $(date)"
          git push -f origin main
     
      - name: Upload file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: job-result
          path: file.txt
